### ISSUE TITLE
demo中情感分析的用例报错

### ISSUE THREAD

**Issue by leo038** [PaddlePaddle/ERNIE#476] opened 2020-05-29 11:34 UTC
运行脚本：

 python3 ./ERNIE-develop/demo/finetune_sentiment_analysis_dygraph.py --from_pretrained ./pretrain_model/    --data_dir ./chnsenticorp/   --max_steps=10000

报错信息：
Traceback (most recent call last):
  File "./ERNIE-develop/demo/finetune_sentiment_analysis_dygraph.py", line 119, in <module>
    for step, d in enumerate(tqdm(dev_ds.start(), desc='evaluating %d' % epoch)):
  File "/home/xxx/ERNIE/ERNIE-develop/propeller/paddle/data/functional.py", line 77, in start
    r.decorate_batch_generator(_gen, places=places)
  File "/home/xxx/.local/lib/python3.6/site-packages/paddle/fluid/reader.py", line 1678, in decorate_batch_generator
    self._loader.set_batch_generator(reader, places)
  File "/home/xxx/.local/lib/python3.6/site-packages/paddle/fluid/reader.py", line 947, in set_batch_generator
    "Number of places must be 1 in dygraph mode"
AssertionError: Number of places must be 1 in dygraph mode

**Comment by Meiyim** [comment] 2020-05-29 13:45
Duplicate of #463 
will fix later.

**Comment by leo038** [comment] 2020-05-30 07:38
> Duplicate of #463
> will fix later.


fixed. Thank you！

**Closed as completed** 2020-05-30 15:30 UTC
Labels: update readme
